Solution
mate-academy/py-cinema-visit pull request #1089
Opened 2024-03-26 17:13 UTC by onyevyerov

2024-03-26 17:26 UTC, viktoria-rybenchuk requested changes

2024-03-28 14:57 UTC, Polyakiv-Andrey requested changes

2024-03-28 14:57 UTC, Polyakiv-Andrey commented on app/main.py
> +def cinema_visit(customers: list,
After opening the parentheses, write each the arguments on a new line, including the first one, the closing bracket is also written on a new line

2024-03-28 14:57 UTC, Polyakiv-Andrey commented on app/main.py
> +    list_of_customers = [Customer(customer["name"], customer["food"])
After opening the parentheses, write each the arguments on a new line, including the first one, the closing bracket is also written on a new line

2024-03-29 13:59 UTC, pavlopro approved these changes
Good Job!

2026-04-10 13:13 UTC, closed without merging