Solution
mate-academy/py-cinema-visit pull request #144
Opened 2022-09-19 13:43 UTC by kateryna3k

2022-09-19 13:52 UTC, wQuelS requested changes

2022-09-19 13:52 UTC, wQuelS commented on app/cinema/hall.py
> +    def movie_session(
add type annotation to function.
If function returns nothing then it is -> None

2022-09-19 13:52 UTC, wQuelS commented on app/main.py
>  def cinema_visit(customers: list, hall_number: int, cleaner: str, movie: str):
same, type annotation

2022-09-19 15:12 UTC, wQuelS approved these changes
Looks awesome imo:)

2022-09-22 11:35 UTC, TPolina approved these changes
Well done!

2024-10-02 07:38 UTC, closed without merging