Solution
mate-academy/py-cinema-visit pull request #372
Opened 2023-02-09 16:18 UTC by oksana0410

2023-02-09 22:34 UTC, skmiwa1 approved these changes
it`s ready to be checked by masters!

2023-02-09 22:34 UTC, skmiwa1 commented on app/people/customer.py
> +
didn`n find anything wrong!
nice!

2023-02-10 09:49 UTC, Y-Havryliv requested changes

2023-02-10 09:49 UTC, Y-Havryliv commented on app/cinema/bar.py
> +    def sell_product(customer: str, product: Customer) -> str:
Does it really return a string?

2023-02-10 09:49 UTC, Y-Havryliv commented on app/cinema/hall.py
> +            customers: list,
```suggestion
            customers: list[Customer],

```

2023-02-10 09:49 UTC, Y-Havryliv commented on app/cinema/hall.py
> +        print(f'"{movie_name}" started in hall number {self.number}.')
add some blank lines before and after for-loop, to make your code more readable

2023-02-10 09:49 UTC, Y-Havryliv commented on app/main.py
> +    guests = [Customer(customer["name"], customer["food"])
same here, make your code more readable

2023-02-10 09:49 UTC, Y-Havryliv commented on app/main.py
> +    hall_num = CinemaHall(hall_number)
it's not `hall_num`, it's `CinemaHall` instance

2023-02-10 09:49 UTC, Y-Havryliv commented on app/main.py
> +    cleaner_name = Cleaner(cleaner)
same here, it's not `cleaner_name`

2023-02-10 09:49 UTC, Y-Havryliv commented on app/people/cinema_staff.py
> +    def clean_hall(self, hall_number: int) -> str:
it returns nothing

2023-02-10 09:49 UTC, Y-Havryliv commented on app/people/customer.py
> +    def watch_movie(self, movie: str) -> str:
it returns nothing

2023-02-10 09:49 UTC, Y-Havryliv commented on app/main.py
> +        customers: list,
```suggestion
        customers: list[dict],
```

2023-02-10 15:28 UTC, YuriiKindrat approved these changes

2025-09-02 07:05 UTC, closed without merging