Solution
mate-academy/py-cinema-visit pull request #424
Opened 2023-03-21 18:23 UTC by Dmytry95

![image](https://user-images.githubusercontent.com/126564500/226705537-8539340c-f8a7-4125-b63e-0ad85e759fcd.png)
не совсем понял этой придирки от Pycharm

2023-03-21 19:07 UTC, katevasilenko commented on app/cinema/bar.py
> +from app.people.customer import Customer
Please add blank line between build-in and your own imports

2023-03-21 19:07 UTC, katevasilenko commented on app/cinema/hall.py
> +from app.people.cinema_staff import Cleaner
The same and also sort your own imports in alphabetical order

2023-03-21 19:07 UTC, katevasilenko commented on app/main.py
> +                 ) -> None:
```suggestion
def cinema_visit(
         customers: list[dict], 
         hall_number: int, 
         cleaner: str, 
         movie: str
 ) -> None:
```

2023-03-21 19:07 UTC, katevasilenko commented on app/main.py
> +cinema_visit(customers, hall_number, cleaner_name, movie)
Please remove debugging from final version

2023-03-21 19:07 UTC, katevasilenko commented on app/cinema/hall.py
> +    ) -> str:
This function return nothing

2023-03-21 19:07 UTC, katevasilenko commented on app/people/cinema_staff.py
> +    def clean_hall(self, hall_number: int) -> str:
This function return nothing

2023-03-21 19:07 UTC, katevasilenko commented on app/people/customer.py
> +    def watch_movie(self, movie: str) -> str:
This function return nothing

2023-03-21 19:09 UTC, katevasilenko requested changes
Please provide those changes

2023-03-22 08:06 UTC, Grayder0152 approved these changes

2023-03-22 08:07 UTC, Grayder0152 commented
> ![image](https://user-images.githubusercontent.com/126564500/226705537-8539340c-f8a7-4125-b63e-0ad85e759fcd.png) не совсем понял этой придирки от Pycharm

Це означає, що ви таке ж ім'я використовуєте в іншому місці, наприклад в боці __main__

2024-05-21 19:16 UTC, closed without merging