solution
mate-academy/py-cinema-visit pull request #447
Opened 2023-03-27 10:23 UTC by YegorT

2023-03-27 10:37 UTC, Bohdan-Salamakha requested changes
don't work on the master branch - bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

2023-03-27 10:58 UTC, YegorT commented
Я не до кіінця впевнений, що добре розумію, що малося на увазі, тому писатиму українською, щоб не заплутатися більше.
Я розумію, що перший комміт відправив з порушенням вимог до рішення. Другий вже був підготовлений належним чином. Отже, я інтерпритував твій коментар як нагадування перечитати вимоги до підготовки рішень задач перед їх пушем і настанову їх дотримуватися. Я вірно тебе зрозумів? Якщо так, то я перечитав гайд знову і пам'ятатиму дотримуватися його надалі.

2023-03-27 11:00 UTC, Bohdan-Salamakha requested changes
don't work on the master branch - bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

2023-03-27 11:48 UTC, ArsenPidhoretskyi requested changes

2023-04-04 11:32 UTC, closed without merging

2023-04-04 11:33 UTC, YegorT commented
I made a new request with a solution on the develop branch