Develop
mate-academy/py-cinema-visit pull request #487
Opened 2023-05-04 21:49 UTC by muriakula

2023-05-05 08:49 UTC, olena-hul requested changes

2023-05-05 08:49 UTC, olena-hul commented on app/cinema/hall.py
> +            cleaning_stuff: AnyStr
cleaning_stuff annotation is wrong

2023-05-05 08:49 UTC, olena-hul commented on app/people/cinema_staff.py
> +    def clean_hall(self, hall_number: AnyStr) -> None:
hall_number annotation is wrong

2023-05-05 08:49 UTC, olena-hul commented on app/cinema/bar.py
> +    def sell_product(product: str, customer: AnyStr) -> None:
customer annotation is wrong

2023-05-06 09:18 UTC, Bohdan-Salamakha approved these changes

2024-10-29 10:10 UTC, closed without merging