Solution
mate-academy/py-cinema-visit pull request #583
Opened 2023-07-10 15:03 UTC by ivanzh13

2023-07-10 15:35 UTC, vsmutok requested changes

2023-07-10 15:35 UTC, vsmutok commented on app/cinema/bar.py
> +
Why you need it?

2023-07-10 20:15 UTC, ivanzh13 commented on app/cinema/bar.py
> +
wrote first, forgot to delete

2023-07-11 09:15 UTC, ArsenPidhoretskyi approved these changes
Well done!

2023-09-18 16:08 UTC, closed without merging