Implement py-cinema-visit
mate-academy/py-cinema-visit pull request #714
Opened 2023-10-05 10:07 UTC by SevKrok

2023-10-05 11:00 UTC, Wonsky1 requested changes

2023-10-05 11:00 UTC, Wonsky1 commented on app/cinema/hall.py
> +    ) -> None:
Add correct type annotiation for "customers"

2023-10-07 22:32 UTC, Wonsky1 approved these changes

2023-10-09 17:27 UTC, LiudmylaKulinchenko requested changes

2023-10-09 17:27 UTC, LiudmylaKulinchenko commented on app/cinema/hall.py
> +            cleaning_staff: Cleaner
too many spaces for indentation

2023-10-09 17:27 UTC, LiudmylaKulinchenko commented on app/main.py
> +        movie: str
too many spaces for indentation

2023-10-09 17:27 UTC, LiudmylaKulinchenko commented on app/main.py
> +    cinema_bar = CinemaBar()
No need to create an instance to call static method

2023-10-09 17:27 UTC, LiudmylaKulinchenko commented on app/main.py
> +    cleaner = Cleaner(cleaner)
Assign variable in the top of function, move it to hall_number assigning

2023-10-10 09:49 UTC, LiudmylaKulinchenko requested changes

2023-10-10 09:49 UTC, LiudmylaKulinchenko commented on app/main.py
> +                 ) -> None:
Fix formatting: brackets must be located in one of two options: open and start with the text or have a line break between the text
Also one parameter in one line to increase readability

2023-10-10 09:49 UTC, LiudmylaKulinchenko commented on app/cinema/hall.py
> +            customers: list,
customers: list[Customer] was fine

2023-10-10 09:49 UTC, LiudmylaKulinchenko commented on app/cinema/hall.py
> +    ) -> None:
```suggestion
    def movie_session(
        self,
        movie_name: str,
        customers: list,
        cleaning_staff: Cleaner
    ) -> None:
```

2023-10-10 18:47 UTC, LiudmylaKulinchenko approved these changes
Good job 👏

2023-10-11 09:48 UTC, closed without merging