solutik
mate-academy/py-cinema-visit pull request #754
Opened 2023-10-17 19:13 UTC by PyCore23

2023-10-18 10:43 UTC, viktoria-rybenchuk requested changes
fix flake8

2023-10-19 09:34 UTC, Dimosphen1 requested changes
Fix flake8 errors and resolve one comment upon the next review request.

2023-10-19 09:34 UTC, Dimosphen1 commented on app/main.py
> +        customers: list,
You could indicate that you expect to obtain a list of dicts for `customers` in type annotation.

2023-10-24 10:59 UTC, viktoria-rybenchuk requested changes

2023-10-24 10:59 UTC, viktoria-rybenchuk commented on app/main.py
> +        cleaner: str[Cleaner.__name__],
```suggestion
        cleaner: str,
```

2023-11-15 13:20 UTC, pavlejviki approved these changes
Good job!

2024-05-17 10:09 UTC, closed without merging